name: se330_project1
description: Software Engineering 330 - Human Factors and User Interface Project 1

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  flutter_bloc: ^3.1.0 
  equatable: ^1.0.0  
  intl: ^0.16.1    
  flutter_secure_storage: ^3.3.1+1  
  http: ^0.12.0+4   
  flutter_tagging: ^1.1.0 
  date_format: ^1.0.8   
  cupertino_icons: ^0.1.2
  flutter_icons: ^1.0.0+1
  sqflite: ^1.2.0
  path_provider: ^1.6.0 
  percent_indicator: "^2.1.1"
  carousel_slider: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

 
flutter:
  
  uses-material-design: true 
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
    - family: Hiragino Mincho ProN
      fonts:
        - asset: fonts/hiragino-mincho-pron-w6.otf
    - family: SF Pro
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-Light.otf
          weight: 200
        - asset: fonts/SF-Pro-Display-Heavy.otf
          weight: 800
  assets: 
    - assets/CanonRebelT7.gif
    - assets/CanonC200EF.jpg 
    - assets/NikonD5.jpg 
    - assets/NikonD3500.jpg
    - assets/JCClogo.jpg
